### ISSUE TITLE
Error on windows-latest runner

### ISSUE THREAD

**Issue by nlamirault** [dawidd6/action-ansible-playbook#67]
I try to use this Github Action using the windows-latest runner. I've got this error : 

```
Run dawidd6/action-ansible-playbook@v2.6.1
C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe collection install -r divona/requirements-windows.yml
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe\__main__.py", line 4, in <module>
  File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\site-packages\ansible\cli\__init__.py", line 42, in <module>
    check_blocking_io()
  File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\site-packages\ansible\cli\__init__.py", line 34, in check_blocking_io
    if not os.get_blocking(fd):
AttributeError: module 'os' has no attribute 'get_blocking'
Error: The process 'C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe' failed with exit code 1
```

do you have an idea about this error ?

**Comment by dawidd6** [comment]
One: it does not seem related to the action.

**Comment by kenorb** [comment]
Related:

- https://github.com/ansible/ansible/issues/79633
- https://github.com/ansible/ansible/pull/79634
